title: Nurlan Musazade 
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I am a doctoral researcher specializing in AI and AI-related skills. My work focuses on understanding how AI tools are used and how they impact analytical and cognitive processes. I have a background in Information Systems and Economics, combining technical and business perspectives. The listed projects are mostly from the Master studies. My current research available at  <a href="https://scholar.google.com/citations?user=OCbib3AAAAAJ&hl=en&oi=ao">Google Scholar</a> and <a href="https://huggingface.co/nurlanm">Hugging Face</a>  
  <br> Finland, Helsinki  <br> 
  <br> +358 46 884 03 29   <br> 
  <br> nurlan.musazade13@gmail.com  <br> 
  <br> <a href="https://www.linkedin.com/in/nurlan-musazade-9b172321a/">LinkedIn</a>  <br>  
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

